# Generated by Django 3.0.5 on 2020-06-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_principal', models.CharField(default='', max_length=255, null=True)),
                ('telefone_principal', models.CharField(default='', max_length=255, null=True)),
                ('usa_twitter', models.BooleanField(default=False)),
                ('url_twitter', models.CharField(default='', max_length=255, null=True)),
                ('usa_facebook', models.BooleanField(default=False)),
                ('url_facebook', models.CharField(default='', max_length=255, null=True)),
                ('usa_instagram', models.BooleanField(default=False)),
                ('url_instagram', models.CharField(default='', max_length=255, null=True)),
                ('usa_whatsapp', models.BooleanField(default=False)),
                ('url_whatsapp', models.CharField(default='', max_length=255, null=True)),
                ('usa_linkdin', models.BooleanField(default=False)),
                ('url_linkdin', models.CharField(default='', max_length=255, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('titulo_sobre', models.CharField(max_length=255)),
                ('mensagem_sobre', models.CharField(max_length=3000)),
                ('imagem_sobre', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
            options={
                'db_table': 'tbPaginaInicial',
            },
        ),
        migrations.AddField(
            model_name='advogado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='funcao',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='url_facebook',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='url_instagram',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='url_linkdin',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='url_twitter',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='url_whatsapp',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usa_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usa_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usa_linkdin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usa_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usa_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Carrocel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mensagem', models.CharField(default='', max_length=1000, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('pagina_inicial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carroceis', to='core.PaginaInicial')),
            ],
            options={
                'db_table': 'tbCarrocel',
            },
        ),
    ]
